### ISSUE TITLE
mysql 无法连接阿里云RDS

### ISSUE THREAD

**Issue by soitun** [Coolpy7/DbPoxy#1]
mysql的连接字符串为：
帐号:密码@rm-2ze8n561w2x07qv89zo.mysql.rds.aliyuncs.com/user?charset=utf8
启动的时候，报如下错：
mysql ping err default addr for network 'rm-2ze8n561w2x07qv89zo.mysql.rds.aliyuncs.com' unknown

请问mysql主机只能填ip吗

**Comment by jacoblai** [comment]
理论上可以直接用阿里云相关地址的，域名默认影射终还是会转为ip给程序使用的，所以应该不会。友情示提：你的密码在这里发了明文，建议你修改你的阿里云mysql密码，以免泄漏。
